"""
Regulation Intelligence Engine for Regulatory Fabric.

Monitors regulatory sources, tracks changes, and provides intelligent analysis.
"""

from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass, field
import threading
import hashlib


@dataclass
class IntelligenceConfig:
    """Configuration for the intelligence engine."""
    update_check_interval_hours: int = 24
    max_sources: int = 100
    retention_days: int = 365
    enable_auto_processing: bool = True
    confidence_threshold: float = 0.7


@dataclass
class IntelligenceAlert:
    """Alert generated by the intelligence engine."""
    alert_id: str
    alert_type: str
    severity: str
    title: str
    description: str
    regulation_id: Optional[str]
    source: str
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)


class RegulationIntelligenceEngine:
    """AI-powered regulation intelligence engine.
    
    Monitors regulatory changes, analyzes impact, and generates alerts.
    """

    def __init__(self, store: Any, config: Optional[IntelligenceConfig] = None):
        """Initialize the intelligence engine.
        
        Args:
            store: Compliance store instance
            config: Engine configuration
        """
        self.store = store
        self.config = config or IntelligenceConfig()
        self._alerts: List[IntelligenceAlert] = []
        self._sources: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()
        self._subscribers: List[Callable[[IntelligenceAlert], None]] = []

    def register_source(self, source_id: str, source_info: Dict[str, Any]) -> bool:
        """Register a regulatory information source.
        
        Args:
            source_id: Unique source identifier
            source_info: Source metadata (name, url, type, etc.)
            
        Returns:
            True if registered successfully
        """
        if len(self._sources) >= self.config.max_sources:
            return False
        
        with self._lock:
            self._sources[source_id] = {
                **source_info,
                "registered_at": datetime.now(timezone.utc),
                "last_check": None,
                "check_count": 0,
            }
        return True

    def subscribe(self, callback: Callable[[IntelligenceAlert], None]) -> None:
        """Subscribe to intelligence alerts.
        
        Args:
            callback: Function to call when alerts are generated
        """
        with self._lock:
            self._subscribers.append(callback)

    def _notify_subscribers(self, alert: IntelligenceAlert) -> None:
        """Notify all subscribers of a new alert."""
        for callback in self._subscribers:
            try:
                callback(alert)
            except Exception:
                pass

    def check_regulatory_updates(self, source_id: Optional[str] = None) -> List[Dict[str, Any]]:
        """Check for new regulatory updates from registered sources.
        
        Args:
            source_id: Optional source ID to check specific source
            
        Returns:
            List of new updates found
        """
        updates_found = []
        sources_to_check = (
            {source_id: self._sources[source_id]} if source_id and source_id in self._sources
            else self._sources
        )
        
        for src_id, source in sources_to_check.items():
            source["last_check"] = datetime.now(timezone.utc)
            source["check_count"] += 1
            
            # Simulate checking for updates (in production, this would call actual APIs)
            new_updates = self._fetch_source_updates(src_id, source)
            updates_found.extend(new_updates)
            
            for update in new_updates:
                self.store.add_regulatory_update(update)
                
                alert = IntelligenceAlert(
                    alert_id=hashlib.md5(f"{update['update_id']}".encode()).hexdigest()[:12],
                    alert_type="REGULATORY_UPDATE",
                    severity=update.get("compliance_impact", "MEDIUM"),
                    title=f"New {update.get('update_type', 'UPDATE')} for {update.get('regulation_id', 'Unknown')}",
                    description=update.get("summary", ""),
                    regulation_id=update.get("regulation_id"),
                    source=src_id,
                )
                self._alerts.append(alert)
                self._notify_subscribers(alert)
        
        return updates_found

    def _fetch_source_updates(self, source_id: str, source: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Fetch updates from a specific source.
        
        In production, this would integrate with actual regulatory APIs.
        
        Args:
            source_id: Source identifier
            source: Source metadata
            
        Returns:
            List of updates found
        """
        # Placeholder - in production, integrate with actual regulatory feeds
        # Examples: SEC EDGAR, EU EUR-Lex, PCI SSC, etc.
        return []

    def analyze_regulation(self, regulation_id: str) -> Dict[str, Any]:
        """Analyze a regulation and generate insights.
        
        Args:
            regulation_id: Regulation to analyze
            
        Returns:
            Analysis results
        """
        regulation = self.store.get_regulation(regulation_id)
        if not regulation:
            return {"error": "Regulation not found"}
        
        controls = self.store.get_controls_for_regulation(regulation_id)
        assessments = self.store.list_assessments(regulation_id=regulation_id)
        risks = self.store.list_risks(regulation_id=regulation_id)
        
        # Calculate coverage metrics
        total_requirements = len(regulation.get("requirements", []))
        mapped_controls = len(controls)
        coverage = (mapped_controls / total_requirements * 100) if total_requirements > 0 else 0
        
        # Calculate compliance rate
        compliant_controls = len([c for c in controls if c.get("status") == "COMPLIANT"])
        compliance_rate = (compliant_controls / len(controls) * 100) if controls else 0
        
        # Risk assessment
        risk_exposure = sum(r.get("risk_score", 0) for r in risks)
        
        return {
            "regulation_id": regulation_id,
            "regulation_name": regulation.get("name"),
            "requirements_count": total_requirements,
            "mapped_controls": mapped_controls,
            "coverage_percentage": round(coverage, 2),
            "compliance_rate": round(compliance_rate, 2),
            "assessments_count": len(assessments),
            "open_risks": len([r for r in risks if r.get("mitigation_status") == "OPEN"]),
            "risk_exposure": round(risk_exposure, 4),
            "recommendations": self._generate_recommendations(regulation, controls, compliance_rate),
        }

    def _generate_recommendations(self, regulation: Dict, controls: List[Dict], compliance_rate: float) -> List[str]:
        """Generate recommendations based on analysis.
        
        Args:
            regulation: Regulation data
            controls: Related controls
            compliance_rate: Current compliance rate
            
        Returns:
            List of recommendations
        """
        recommendations = []
        
        if compliance_rate < 50:
            recommendations.append("Critical: Immediate remediation required for compliance gaps")
        elif compliance_rate < 80:
            recommendations.append("High: Address remaining compliance gaps within 30 days")
        
        unmapped = [r for r in regulation.get("requirements", []) if not any(
            c.get("mapping", {}).get("requirement_id") == r.get("id") for c in controls
        )]
        if unmapped:
            recommendations.append(f"Map {len(unmapped)} unmapped requirements to controls")
        
        return recommendations

    def get_alerts(self, severity: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
        """Get recent intelligence alerts.
        
        Args:
            severity: Optional severity filter
            limit: Maximum number of alerts to return
            
        Returns:
            List of alerts
        """
        alerts = self._alerts
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        return [
            {
                "alert_id": a.alert_id,
                "alert_type": a.alert_type,
                "severity": a.severity,
                "title": a.title,
                "description": a.description,
                "regulation_id": a.regulation_id,
                "source": a.source,
                "generated_at": a.generated_at.isoformat(),
            }
            for a in alerts[-limit:]
        ]

    def predict_compliance_impact(self, regulatory_update: Dict[str, Any]) -> Dict[str, Any]:
        """Predict the compliance impact of a regulatory update.
        
        Args:
            regulatory_update: The regulatory update to analyze
            
        Returns:
            Impact prediction
        """
        affected_reqs = regulatory_update.get("affected_requirements", [])
        impact_level = regulatory_update.get("compliance_impact", "MEDIUM")
        
        # Calculate affected controls
        affected_controls = 0
        for mapping in self.store.control_mappings.values():
            if mapping.get("requirement_id") in affected_reqs:
                affected_controls += 1
        
        # Estimate remediation effort
        effort_map = {"LOW": 1, "MEDIUM": 3, "HIGH": 5, "CRITICAL": 8}
        estimated_days = effort_map.get(impact_level, 3) * max(1, affected_controls)
        
        return {
            "update_id": regulatory_update.get("update_id"),
            "affected_requirements": len(affected_reqs),
            "affected_controls": affected_controls,
            "impact_level": impact_level,
            "estimated_remediation_days": estimated_days,
            "priority": "CRITICAL" if affected_controls > 10 else impact_level,
            "required_actions": self._generate_required_actions(regulatory_update),
        }

    def _generate_required_actions(self, update: Dict[str, Any]) -> List[str]:
        """Generate required actions for an update.
        
        Args:
            update: Regulatory update
            
        Returns:
            List of required actions
        """
        actions = []
        actions.append("Review updated requirements")
        actions.append("Assess impact on existing controls")
        
        if update.get("effective_date"):
            days_until = (update["effective_date"] - datetime.now(timezone.utc)).days
            if days_until > 0:
                actions.append(f"Plan remediation before {days_until} days")
        
        return actions


def get_intelligence_engine() -> RegulationIntelligenceEngine:
    """Get the global intelligence engine instance."""
    from .store import get_compliance_store
    store = get_compliance_store()
    return RegulationIntelligenceEngine(store)